services:
    nginx:
      image: nginx
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/webhook-0-bot.conf:/etc/nginx/bots/webhook-0-bot.conf
      ports:
        - 8080:80

    echo-bot:
      build:
        context: ./echo_bot

      logging:
        options:
          max-size: "1m"
          max-file: "3"

      volumes:
        - ./echo_bot:/app

      # command: sleep 10000
      # command: python /app/main.py
      command: supervisord -c /app/supervisord.conf

      environment:
        ABC: "ABC"

      env_file:
        - .env

      secrets:
        - echo_bot.env

    echo-bot-webhook:
      build:
        context: ./echo_bot_webhook

      logging:
        options:
          max-size: "1m"
          max-file: "3"

      volumes:
        - ./echo_bot_webhook:/app

      # command: sleep 10000
      command: supervisord -c /app/supervisord.conf

      environment:
        ABC: "ABC"

      env_file:
        - .env

      secrets:
        - echo_bot_webhook.env

    postgres:
        restart: always    
        image: postgres
    
        environment:
          - POSTGRES_USER=bot
          - POSTGRES_PASSWORD=123
          - POSTGRES_DB=bot
          
        volumes:
          - ./postgres/postgres-data:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        hostname: redis
        command: redis-server
        labels:
          NAME: redis

secrets:
  echo_bot.env:
    file: secrets/echo_bot.env
  echo_bot_webhook.env:
    file: secrets/echo_bot_webhook.env

#   t2s.json:
#     file: call_receiver/secrets/t2s.json

